### ISSUE TITLE
Archlinux package

### ISSUE THREAD

**Issue by Yamakaky** [rsolomo/cargo-check#1]
https://aur4.archlinux.org/packages/cargo-check-git/

You should disable the compilation of `main` during the tests using `#[cfg(not(test))]` to remove the warning. And you should put the tests in a module, see http://doc.rust-lang.org/book/testing.html.

**Comment by Byron** [comment]
If #2 is merged, `cargo test` compiles without warnings. It seems tests don't have to be in a module to be excluded during normal compilation thanks to `#[test]`. I tried putting them in a module (i.e. `#[cfg(test)] mod tests {...}`, but found this only reduced the code's maintainability as it adds visual noise.

**Comment by Yamakaky** [comment]
Cool !

**Comment by rsolomo** [comment]
resolved by #2
