### ISSUE TITLE
Support both [[bin]] and [lib] together?

### ISSUE THREAD

**Issue by dpc** [rsolomo/cargo-check#4]
```
% cargo check
extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
```

Isn't there any way to support both `[[bin]]` and `[lib]` in one go? `cargo build` just works, so I'd expect `cargo check` to be drop-in replacement.

**Comment by rsolomo** [comment]
Yeah, this is the same error message that you'll receive if you ran `cargo rustc -- -Zno-trans`.

I normally work around this by doing something like `cargo check --lib`.
I'm not sure if there is a way to get `cargo rustc` to behave more like `cargo build` when it comes to this.

**Comment by dpc** [comment]
Maybe we should escalate to cargo devs?

**Comment by natemara** [comment]
The problem with always running `cargo check --lib` is that it excludes the main.rs file if you have one. This means that there currently isn't a way to run a generic `cargo check` command that will automatically build the project for editor linter support. A bit disappointing. I suppose I'll go back to `cargo build`.

**Comment by Furyhunter** [comment]
My workaround for this was to split my project into several crates, with the top-level crate being bin-only and the rest being libs. However, this means that you have to append `-p` to your `check` invocation to lint the other crates.

**Comment by bruno-medeiros** [comment]
And what about the tests targets... I wanna check those too. :disappointed:
